---
- hosts: mywebservers
  become: yes
  tasks: 
  - name: i want to install webserver on ubuntu
    apt:
      name: apache2
      state: started
    when: ansible_os_family=="Debian"

  - name: i want to start webserver redhat
    service:
      name: httpd
      state: present
    when: ansible_os_family=="RedHat"

  - name: i want install webserver on RedHat
    yum: 
      name: httpd
      state: started
    when: ansible_os_family=="Redhat"
  
