---
- hosts: mynewhosts
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: create folder
    file:
     path: /home/ubuntu/myfolder
     state: directory
  - name: copy file from master to node side
    copy:
     src: myfile.txt
     dest: /home/ubuntu/my2ndfile