---
- hosts: mynewhosts
  become: yes
  gather_facts: yes
  tasks: 
  - name: i want to install apache2 webserver on ubuntu ansible nodes
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"

  - name: i want to install wget
    apt: 
     name: wget
     state: present 
    when: ansible_os_family=="Debian"

  - name: i want webserver
     services:
       name: apache2
       state: started
     when: ansible_os_family=="Redhat"
    
   

  

  