---
- hosts: 172.31.29.6
  become: yes
  tasks:
   - name: i want install git
     apt:
      name: git
      state: present
     tags: git
     
   - name: i want to install wget
     apt:
      name: wget
      statee: present
     tags: wget


   - name: i want to install tree
     apt:
      name: tree
      state: present
     tags: tree